--- #YAML:1.0
name:                WWW-Search-Mininova
version:             0.04
abstract:            Interface to www.mininova.org Torrent site
license:             ~
author:              
    - Zoffix Znet <cpan@zoffix.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    HTML::Entities:                1.35
    HTML::TokeParser::Simple:      3.15
    LWP::UserAgent:                2.036
    URI:                           1.35
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
